#!/bin/bash

export -A dict=(
	# APT
	["apt_sys"]="Install Sys APT Packages"
	["apt_key"]="Install Key APT Packages"
	["apt_dev"]="Install Dev APT Packages"
	["apt_gui"]="Install GUI APT Packages"

	# .deb
	["zoom"]="Install Zoom"
	["google-chrome-stable"]="Install Chrome"
	["discord"]="Install Discord"
	["quickemu"]="Install Quickemu"
	["obsidian"]="Install Obsidian"
	["typora"]="Install Typora.io"

	# Node.js
	["nvm"]="Fetch && Install NVM"
	["npm"]="Fetch && Install NPM"

	# nvim
	["nvim"]="Install Neovim"

	# Docker
	["docker"]="Install Docker"

	# Anki
	["anki"]="Anki > ~/Downloads"

	# v2rayA
	["v2raya"]="Install v2rayA"
	["xray"]="Install Xray-core"

	# The End
	["the_end"]="Installation Completed"
)
