#!/bin/bash

set -euo pipefail

. "${BASH_SOURCE%/*}"/"stages/apt"
. "${BASH_SOURCE%/*}"/"stages/deb"
. "${BASH_SOURCE%/*}"/"stages/docker"
. "${BASH_SOURCE%/*}"/"stages/nodejs"
. "${BASH_SOURCE%/*}"/"stages/nvim"
. "${BASH_SOURCE%/*}"/"stages/the_end"
