#!/bin/bash

export KEY_PACKAGES=(
	gcc
	make
	cmake
	cargo
	curl
	wget
	ffmpeg

	# lc0
	meson
	libopenblas-dev

	# wasm
	clang-22
	lld-22
	llvm-22
	clang-tidy-22
	clang-format-22
	libclang-rt-22-dev
)
