#!/bin/bash

add_padding() {
	local target_length=$1
	shift
	local input="$@"

	local input_length=${#input}
	local total_spaces=$((target_length - input_length))
	local left_spaces=$((total_spaces / 2))
	local right_spaces=$((total_spaces - left_spaces))

	printf "%*s%s%*s" $left_spaces "" "$input" $right_spaces ""
}

print_header() {
	local input=$(add_padding 26 "$@")

	local green="\033[0;32m"
	local reset="\033[0m"

	echo -e "\t${green}"

	cat << "EOF"
	⣿⣿⢃⣾⢿⣿⠿⠛⠻⣿⣿⡿⢿⣿⣿⣿⣿⣿⣷⡘⢿⣿⣿⣿⣿⣿⣿⠟
	⣿⠃⣾⠃⡼⣩⣶⣿⣷⡜⣿⣇⢳⣍⠻⢿⣿⣿⣿⣿⡈⣿⣿⣿⣿⠿⠉⣀
	⡏⣼⣿⢈⣴⣿⣿⣿⣿⣿⣎⡛⠌⢿⣿⣶⣦⠍⣉⣛⣓⢸⣿⣿⣿⡆⣬⠙
	⡃⣿⣿⡸⣿⣿⣌⠻⢿⣿⣿⣿⣷⣾⣿⠿⣡⣾⣿⣿⣿⡇⢿⣿⣿⡇⣙⢡
	⣧⡉⠭⠥⠘⣿⣿⠿⢷⣾⣿⣿⣿⣿⣷⣾⢋⣥⣾⣿⣿⡇⢸⣿⡟⣰⣿⠸
	⣿⣿⡆⣭⡅⢻⣧⠄⢈⣿⣿⣿⡿⠿⠿⢿⣿⣿⣿⣿⣿⢇⣿⡿⠇⣿⣿⠰
	⠿⢛⣵⡿⢓⣾⣿⣿⣿⣿⣿⢫⣶⣿⣿⡆⣿⣿⣿⡿⢋⡾⠛⠄⠄⣿⣿⡎
	⣷⣌⡋⢘⣋⣿⣿⣿⣿⣿⣿⣆⢿⣿⠟⣰⣿⣿⣿⡧⠄⣼⣿⣿⣿⣿⣿⣿
	⣿⡿⢡⣾⣿⢂⣉⠛⢿⣿⣿⣿⣷⣶⣾⣿⣿⣿⠟⢱⢰⣶⣶⣿⣿⣿⣿⣿ 
EOF

	echo -e "\n\t~$input~$reset\n"
}
