#!/bin/bash

print_header() {
	local ascii="
⣿⣿⢃⣾⢿⣿⠿⠛⠻⣿⣿⡿⢿⣿⣿⣿⣿⣿⣷⡘⢿⣿⣿⣿⣿⣿⣿⠟
⣿⠃⣾⠃⡼⣩⣶⣿⣷⡜⣿⣇⢳⣍⠻⢿⣿⣿⣿⣿⡈⣿⣿⣿⣿⠿⠉⣀
⡏⣼⣿⢈⣴⣿⣿⣿⣿⣿⣎⡛⠌⢿⣿⣶⣦⠍⣉⣛⣓⢸⣿⣿⣿⡆⣬⠙
⡃⣿⣿⡸⣿⣿⣌⠻⢿⣿⣿⣿⣷⣾⣿⠿⣡⣾⣿⣿⣿⡇⢿⣿⣿⡇⣙⢡
⣧⡉⠭⠥⠘⣿⣿⠿⢷⣾⣿⣿⣿⣿⣷⣾⢋⣥⣾⣿⣿⡇⢸⣿⡟⣰⣿⠸
⣿⣿⡆⣭⡅⢻⣧⠄⢈⣿⣿⣿⡿⠿⠿⢿⣿⣿⣿⣿⣿⢇⣿⡿⠇⣿⣿⠰
⠿⢛⣵⡿⢓⣾⣿⣿⣿⣿⣿⢫⣶⣿⣿⡆⣿⣿⣿⡿⢋⡾⠛⠄⠄⣿⣿⡎
⣷⣌⡋⢘⣋⣿⣿⣿⣿⣿⣿⣆⢿⣿⠟⣰⣿⣿⣿⡧⠄⣼⣿⣿⣿⣿⣿⣿
⣿⡿⢡⣾⣿⢂⣉⠛⢿⣿⣿⣿⣷⣶⣾⣿⣿⣿⠟⢱⢰⣶⣶⣿⣿⣿⣿⣿"

	printf "\033[0;32m" # Green

	echo "${ascii//$'\n'/$'\n\t'}"

	local width=$(($(echo "$ascii" | wc -L) - 2))

	local text="$*"
	local left_pad=$(((width - ${#text}) / 2))
	local right_pad=$((width - ${#text} - left_pad))

	printf "\n\t~%*s%s%*s~\033[0m\n\n" $left_pad "" "$text" $right_pad ""
}
