#!/bin/bash

. "${BASH_SOURCE%/*}"/"../dict"
. "${BASH_SOURCE%/*}"/"print_header"

wget_install() {
	local key=$1
	local url=$2

	if dpkg-query -W -f='${Status}' "$key" 2>/dev/null | grep -q "install ok installed"; then
		echo "$key is already installed, skipping"
		return
	fi

	local temp_dir
	temp_dir=$(mktemp -d)

	print_header "${dict[$key]}"

	wget -q --show-progress -O "${temp_dir}/$key.deb" "$url"
	sudo apt install -y "${temp_dir}/$key.deb"

	rm -rf "$temp_dir"
}
