#!/bin/bash

. $(dirname $BASH_SOURCE)/"../dict"
. $(dirname $BASH_SOURCE)/"../utils/print_header"

print_header ${dict["anki"]}
url="https://github.com/ankitects/anki/releases/download/25.07.5/anki-launcher-25.07.5-linux.tar.zst"

temp_dir=$(mktemp -d)

wget -q --show-progress -O "$temp_dir/anki.tar.zst" $url

tar xaf "$temp_dir/anki.tar.zst" -C "$HOME/Downloads"

rm -rf "$temp_dir"
