#!/bin/bash

. "${BASH_SOURCE%/*}"/"../dict"
. "${BASH_SOURCE%/*}"/"../utils/print_header"
. "${BASH_SOURCE%/*}"/"../utils/gh_latest_version"

print_header "${dict["anki"]}"
version=$(gh_latest_version ankitects/anki)
url="https://github.com/ankitects/anki/releases/download/${version}/anki-launcher-${version}-linux.tar.zst"

temp_dir=$(mktemp -d)

wget -q --show-progress -O "$temp_dir/anki.tar.zst" "$url"

tar xaf "$temp_dir/anki.tar.zst" -C "$HOME/Downloads"

rm -rf "$temp_dir"
