#!/bin/bash

. $(dirname $BASH_SOURCE)/"../dict"
. $(dirname $BASH_SOURCE)/"../utils/print_header"

SYS_PACKAGES=(
	xorg
	i3

	systemd-timesyncd

	pulseaudio
	pavucontrol

	network-manager
	network-manager-applet

	libnotify-bin

	brightnessctl

	arandr
	feh

	ibus

	# GTK (Graphite)
		lxappearance
		gnome-themes-extra
		gtk2-engines-murrine
		sassc
)

KEY_PACKAGES=(
	gcc
	make
	cargo
	curl
	wget
	ffmpeg

	# quickemu
		genisoimage
		jq
		mesa-utils
		qemu-system
		socat
		spice-client-gtk
		swtpm
		uuid-runtime
		zsync

	# google-chrome
		fonts-liberation

	# lc0
		meson
	
	# zoom
		libxcb-xtest0 
)

DEV_PACKAGES=(
	autojump
	tree
	sqlite3
	tmux

	# nvim
		xclip
		ripgrep
		unzip
		python3.13-venv
		rsync
)

GUI_PACKAGES=(
	firefox-esr
	epiphany-browser
	transmission

	flameshot
	obs-studio
	shotcut
	screenkey

	thunar
	atril
	fontforge

	scid
)

install_packages() {
	local key=$1
	shift
	local packages=($@)

	print_header ${dict[$key]}
	sudo apt install ${packages[@]}
}

install_packages "apt_sys" ${SYS_PACKAGES[@]}
install_packages "apt_key" ${KEY_PACKAGES[@]}
install_packages "apt_dev" ${DEV_PACKAGES[@]}
install_packages "apt_gui" ${GUI_PACKAGES[@]}
