#!/bin/bash

. "${BASH_SOURCE%/*}"/"../dict"
. "${BASH_SOURCE%/*}"/"../utils/print_header"

. "${BASH_SOURCE%/*}"/"apt.d/sys"
. "${BASH_SOURCE%/*}"/"apt.d/key"
. "${BASH_SOURCE%/*}"/"apt.d/dev"
. "${BASH_SOURCE%/*}"/"apt.d/gui"

install_packages() {
	local key=$1
	shift
	local packages=("$@")

	print_header "${dict[$key]}"
	sudo apt install -y "${packages[@]}"
}

install_packages "apt_sys" "${SYS_PACKAGES[@]}"
install_packages "apt_key" "${KEY_PACKAGES[@]}"
install_packages "apt_dev" "${DEV_PACKAGES[@]}"
install_packages "apt_gui" "${GUI_PACKAGES[@]}"
