#!/bin/bash

. "${BASH_SOURCE%/*}"/"../dict"
. "${BASH_SOURCE%/*}"/"../utils/print_header"

print_header "${dict["cisco"]}"

url="https://uci.service-now.com/sys_attachment.do?sys_id=e177783eeb516e501059f2acbad0cd34"
temp_dir=$(mktemp -d)

wget -q --show-progress -O "$temp_dir/cisco-vpn.tar.gz" "$url"
tar xzvf "$temp_dir/cisco-vpn.tar.gz" -C "$temp_dir"

# Find the extracted folder (assuming only one folder was extracted)
vpn_dir=$(find "$temp_dir" -mindepth 1 -maxdepth 1 -type d | head -1)

(cd "$vpn_dir/vpn" && sudo ./vpn_install.sh)
rm -rf "$temp_dir"
