#!/bin/bash

. $(dirname $BASH_SOURCE)/"../utils/wget_install"

declare -A candidates=(
	[chrome]=https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
	[discord]=https://stable.dl2.discordapp.net/apps/linux/0.0.102/discord-0.0.102.deb
	[quickemu]=https://github.com/quickemu-project/quickemu/releases/download/4.9.7/quickemu_4.9.7-1_all.deb
	[obsidian]=https://github.com/obsidianmd/obsidian-releases/releases/download/v1.8.10/obsidian_1.8.10_amd64.deb
)

for key in "${!candidates[@]}"; do
	wget_install $key ${candidates[$key]}
done
