#!/bin/bash

. "${BASH_SOURCE%/*}"/"../dict"
. "${BASH_SOURCE%/*}"/"../utils/print_header"
. "${BASH_SOURCE%/*}"/"../versions.conf"

print_header "${dict["nvm"]}"

mkdir "$HOME/.config/nvm"
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/"${NVM_VERSION}"/install.sh | bash

print_header "${dict["npm"]}"

source "$NVM_DIR/nvm.sh"

nvm install --lts
npm install -g pnpm pm2 nodemon sort-package-json @johnnymorganz/stylua-bin tree-sitter-cli
