#!/bin/bash

. $(dirname $BASH_SOURCE)/"../dict"
. $(dirname $BASH_SOURCE)/"../utils/print_header"

print_header ${dict["nvim"]}

url="https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz"
temp_dir=$(mktemp -d)

wget -q --show-progress -O "${temp_dir}/nvim.tar.gz" "$url"
sudo rm -rf /opt/nvim
sudo tar -C /opt -xzf "${temp_dir}/nvim.tar.gz"
rm -rf "$temp_dir"
