#!/bin/bash

. "${BASH_SOURCE%/*}"/"../dict"
. "${BASH_SOURCE%/*}"/"../utils/print_header"
. "${BASH_SOURCE%/*}"/"../utils/wget_install"
. "${BASH_SOURCE%/*}"/"../versions.conf"

GH="https://github.com"

wget_install "v2raya" \
  "$GH/v2rayA/v2rayA/releases/download/v${V2RAYA_VERSION}/installer_debian_x64_${V2RAYA_VERSION}.deb"

print_header "${dict["xray"]}"
sudo bash -c "$(curl -L "$GH/XTLS/Xray-install/raw/main/install-release.sh")" -- install
